import Header from "@/components/Header";
import Providers from "@/utils/provider";
import React from "react";
import "./globals.css";

export const metadata = {
  title: "Ocarz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-primary">
          <main className="m-auto w-[90vw]">
            <Header />
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
