import Header from "@/components/Header";
import Providers from "@/utils/provider";
import React from "react";
import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Ocarz",
  description: "Generated by create next app",
};

import { Comfortaa } from "next/font/google";
// import from public
// const axis = localFont({ src: './fonts/Axis_Extrabold.otf' , variable: '--font-axis',
// });
export const myFont = localFont({
  src: "../fonts/Axis_Extrabold.otf",
  display: "swap",
});
// If loading a variable font, you don't need to specify the font weight
const comfortaa = Comfortaa({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${comfortaa.className}`}>
      <body>
        <div className="bg-primary">
          <main className="m-auto w-[90vw]">
            <Header />
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
